### ISSUE TITLE
[后端框架] 初始化项目

### ISSUE THREAD

**Issue by Victarry** [nkucs/server#1]

**Comment by loveklmn** [comment]
添加一下`readme`吧
比如 启动前
`pip3 install -r requirements.txt`

**Comment by VERSPD0** [comment]
文档请查看[Wiki](https://github.com/nkucs/server/wiki/%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3)  @loveklmn

**Comment by Aya99code** [comment]
把文档在哪查看在Readme里加一下吧，想不到帮助文档在wiki那啊

**Comment by Victarry** [comment]
> 把文档在哪查看在Readme里加一下吧，想不到帮助文档在wiki那啊

Fixed #44
