### ISSUE TITLE
{开发-6.1}[管理员模块][课程管理](王昕蕊)实现获取当前学期课程的API

### ISSUE THREAD

**Issue by CaesarKingW** [nkucs/server#150]

**Comment by LGH1gh** [comment]
request : {
    "teacherId": 1
}

response : {
    courseList: [{
        "courseId": 1
        "courseName": Java
        "courseDescription: "本课程针对大二学生开设，主要介绍..."
    }, {
         "courseId": 2
        "courseName": C++
        "courseDescription: "本课程针对大二学生开设，主要介绍..."
    }]
}
